### ISSUE TITLE
Can only test files in the linus/doctest repository, not in my own project

### ISSUE THREAD

**Issue by suncom-nelson-blocker** [linus/doctest#1]
When supplying a file name to test, the file name is appended to the URL of the doctest repository. If I want to test a file named "hello.js", the test looks for the file "https://deno.land/x/doctest@0.1.3/hello.js" instead of in my own project.

**Comment by linus** [comment]
Thank you @suncom-nelson-blocker! Welp, that's embarrassing. I guess that's what happens when you _only_ dogfood 😳 

I will work with @kristofferjansson on his PR in #2 and resolve this asap.

**Comment by linus** [comment]
Thanks again @suncom-nelson-blocker, this has been fixed with #2. I will issue a new release.
